### ISSUE TITLE
dev server does not obey command line options

### ISSUE THREAD

**Issue by parthjoshi2007** [hendrix/hendrix#155]
There is a very trivial bug in `hendrix/options.py` on [line 26 in the `cleanOptions` function](https://github.com/hendrix/hendrix/blob/85f97bfc573f5dc38ba51fd787bbfecb0dfeeccd/hendrix/options.py#L26) where the return statement is inside the for loop when it should be outside

This prevents the dev server from preserving almost all of the option settings when it reloads on filesystem changes resulting in the dev server not obeying any of the command line options.

**Comment by jMyles** [comment]
Hey @parthjoshi2007, thanks for opening this!  (and the apparent manifestation, #154).  

Looks like you've got a WIP to fix it - care to open a PR?

For context: I think that most of us who are using hendrix in Python 3 are instantiating a `HendrixDeploy` object directly rather than using the `hx` binary, so sadly this may have just slipped between the cracks.  How embarassing! :-)

**Comment by mpasternak** [comment]
I do! https://github.com/hendrix/hendrix/pull/159
